name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
          - name: General
            uses: lowlighter/metrics@latest
            with:
              # Your GitHub token
              # The following scopes are required:  
              #  - public_access (default scope)
              # The following additional scopes may be required:
              #  - read:org      (for organization related metrics)
              #  - read:user     (for user related data)
              #  - read:packages (for some packages related data)
              #  - repo          (optional, if you want to include private repositories)
              token: ${{ secrets.METRICS_TOKEN }}
              config_output: png
              filename: github-metrics.png
              user: Rak1ta
              template: classic
              base: header, activity, community, repositories, metadata
              config_timezone: Europe/Moscow
              repositories_skipped: Rak1ta/Rak1ta
              config_display: columns
              
